image: gcc

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "web"'
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - static_analysis
  - unit_tests

clang-format:
  stage: static_analysis
  before_script:
    - apt-get update
    - apt-get install -y clang-format git
  script:
    - find . -type f -maxdepth 1 -iname "*.cpp" -o -iname "*.h" | xargs clang-format -i --style=file
    - git update-index -q --refresh
    - |
      git diff-index --exit-code HEAD || {
        ret=$?
        echo "Inconsistent formatting, please apply patch from artifacts"
        git diff > correct-formatting.patch
        exit $ret
      }
  artifacts:
    paths:
      - correct-formatting.patch
    when: on_failure
    expire_in: 1 week
  allow_failure: true

googletest:
  stage: unit_tests
  before_script:
    - apt-get update
    - apt-get install -y git make
  script:
    - git submodule update --init --recursive
    - cd tests
    - make
    - find . -maxdepth 1 -type f -executable -exec {} \;
  allow_failure: false
